---
- name: Generate HTML file
  hosts: localhost
  vars_files:
    - ../vault/page_variables.yml
  tasks:

    - name: Get current timestamp
      set_fact:
        current_time: "{{ ansible_date_time.iso8601 }}"

    - name: Generate UUID from current timestamp
      set_fact:
        current_time_uuid: "{{ current_time | to_uuid }}"

    - name: Build index html page
      ansible.builtin.template:
        src: ../templates/index.html.j2
        dest: ../../docs/index.html

    # Perform rest of git commands
    - name: git add commit additional commands
      include_tasks: ../common_tasks/git_add_commit_additional.yml
      