  - name: git add .
    shell: "git add ."
    args:
      chdir: "{{ ansible_env.PWD }}/../.."

  - name: "git commit -m {{ current_time_uuid }}"
    shell: "git commit -m \"{{ current_time_uuid }}\""
    args:
      chdir: "{{ ansible_env.PWD }}/../.."

  - name: git branch -M main
    shell: "git branch -M main"
    args:
      chdir: "{{ ansible_env.PWD }}/../.."

  - name: git push origin main
    shell: "git push origin main"
    args:
      chdir: "{{ ansible_env.PWD }}/../.."