drupalvr:
  template: single_page.html.j2
  url: drupal-for-vr.html
  content:
      breadcrumbs:
        -
          url: index.html
          link: Home
        -
          url: drupal-for-vr.html
          link: Drupal for VR
      title: "Drupal for VR"
      header: "Using a CMS for creating VR content"
      header_image:
        src: "./images/drupal_for_vr/drupal-banter.png"
        alt: "Logo combination of Drupal and Banter"
      content: |
        <div>
          <h2>Building VR Content with Drupal for the Banter VR application</h2>
          <p>
            <a href="https://bantervr.com/">Banter</a> is a Social VR platform, please see the <a href="https://craigmoore.github.io/banter.html">Banter page</a> for more information.
          </p>
          <p>
            As the spaces built within Banter are entirely web-based, Drupal can provide a unique and powerful way to build such content using ThreeJS and A-Frame.
          </p>
          <p>
            This is a project currently in progress, so this page includes some example screenshots :
          </p>
          <h2>
            Configuring "ActiveObjects" within Drupal
          </h2>
          <p>
            An "ActiveObject" is an abstract concept that represents an object that will be represented at runtime within a ThreeJS or Banter Scene. Within Drupal, the fields required to construct an ActiveObject represent the fields to store the data against entities within Drupal. By default, we have created an entity of type "Node" and a bundle of type "ActiveObject", and we have attached various "ActiveObject Components" (represented in Drupal as fields) to the entity bundle.
          </p>
          <p>
            <a href="./images/drupal_for_vr/active-object-configuration.png" data-lightbox="active-object-configuration" data-title="Screenshot of a web page with the ThreeJS component configuration form exposed.">
              <img src="./images/drupal_for_vr/active-object-configuration.png" alt="Screenshot of a web page with the ThreeJS component configuration form exposed." />
            </a>
          </p>
          <h2>
            Drupal Fields as attached to an entity bundle
          </h2>
          <p>
            <a href="./images/drupal_for_vr/active-object-fields.png" data-lightbox="active-object-fields" data-title="Screenshot of a web page with the Drupal Fields of ActiveObject Fields attached.">
              <img src="./images/drupal_for_vr/active-object-fields.png" alt="Screenshot of a web page with the Drupal Fields of ActiveObject Fields attached." />
            </a>
          </p>
          <h2>
            Create a scene with Mr Doobs ThreeJS editor
          </h2>
          <p>
            <a href="./images/drupal_for_vr/mrdoobs-three-js-editor.png" data-lightbox="mrdoobs-three-js-editor" data-title="Screenshot of a web page with Mr Doobs ThreeJS Editor." />          
              <img src="./images/drupal_for_vr/mrdoobs-three-js-editor.png" alt="Screenshot of a web page with Mr Doobs ThreeJS Editor." />
            </a>
          </p>
          <p>
            ThreeJS content can be created and laid out in 3D using Mr Doobs ThreeJS and then exported as a Scene JSON file.
          </p>
          <h2>
            Importing the scene into Drupal
          </h2>
          <p>
            The Scene can then be imported into Drupal using a Drush command.
          </p>
          <p>
            <a href="./images/drupal_for_vr/drush-scene-import.png" data-lightbox="drush-scene-import" data-title="Screenshot of VSCode using a drush command to import a scene into Drupal" />
              <img src="./images/drupal_for_vr/drush-scene-import.png" alt="Screenshot of VSCode using a drush command to import a scene into Drupal" />
            </a>
            <a href="./images/drupal_for_vr/mrdoobs-three-js-imported-objects.png" data-lightbox="mrdoobs-three-js-imported-objects" data-title="Screenshot of a web page within Drupal showing ActiveObject entities as imported into Drupal" />
              <img src="./images/drupal_for_vr/mrdoobs-three-js-imported-objects.png" alt="Screenshot of a web page within Drupal showing ActiveObject entities as imported into Drupal" />
            </a>
          </p>
          <h2>
            Viewing the content within Drupal
          </h2>
          <p>
            Once the objects have been imported into Drupal, they can be edited using normal entity edit forms and viewed on a page. At the moment, a typical ThreeJS formatter has been implemented, and then that formatter has been extended to integrate with A-Frame (and thus the Banter application).
          </p>
          <p>
            This is how the scene looks in a piece of Drupal content :
          </p>
          <p>
            <a href="./images/drupal_for_vr/active-objects-displayed-on-page.png" data-lightbox="active-objects-displayed-on-page" data-title="Screenshot of a web page showing a 3D scene as loaded by ThreeJS / Aframe for consumption on the web" />
              <img src="./images/drupal_for_vr/active-objects-displayed-on-page.png" alt="Screenshot of a web page showing a 3D scene as loaded by ThreeJS / Aframe for consumption on the web" />
            </a>
          </p>
          <p>
            This is how the scene looks in Banter :
          </p>
          <p>
            <a href="./images/drupal_for_vr/mrdoobs-imported-objects-in-banter.png" data-lightbox="mrdoobs-imported-objects-in-banter" data-title="Screenshot of Banter showing the 3D scene" />
              <img src="./images/drupal_for_vr/mrdoobs-imported-objects-in-banter.png" alt="Screenshot of Banter showing the 3D scene" />
            </a>
          </p>
          <h2>
            Using GLTF assets
          </h2>
          <p>
            ThreeJS and Banter support many file formats, that can be uploaded into Drupal, mapped to the ActiveObject field using the Token Module and displayed. This first image shows the creation of a piece of content representing a GLTF model, and the following image shows the "Khronos Duck" imported into Drupal as a file field and mapped using [node:field_activeobject_file:entity:url] as the Token mapping. Token Replace is applied during use of the JSON:API.
          </p>
          <p>
            <a href="./images/drupal_for_vr/creating-duck-gltf-active-object.png" data-lightbox="creating-duck-gltf-active-object" data-title="Screenshot of a web page within Drupal showing the creation of an ActiveObject representing the Khronos Duck" />
              <img src="./images/drupal_for_vr/creating-duck-gltf-active-object.png" alt="Screenshot of a web page within Drupal showing the creation of an ActiveObject representing the Khronos Duck" />
            </a>
            <a href="./images/drupal_for_vr/creating-duck-active-object-2-showing-mapping.png" data-lightbox="creating-duck-active-object-2-showing-mapping" data-title="Screenshot of a web page within Drupal showing applying a token to map a file field" />
              <img src="./images/drupal_for_vr/creating-duck-active-object-2-showing-mapping.png" alt="Screenshot of a web page within Drupal showing applying a token to map a file field" />
            </a>
          </p>
          <h2>
            <a href="./images/drupal_for_vr/riding-a-duck-in-banter.png" data-lightbox="riding-a-duck-in-banter" data-title="Screenshot of the Banter application showing the user on the back of the Khronos duck" />
              <img src="./images/drupal_for_vr/riding-a-duck-in-banter.png" alt="Screenshot of the Banter application showing the user on the back of the Khronos duck" />
            </a>
          </h2>
        </div>

      footer: "Banter is created by <a href=\"https://sidequestvr.com/\">SideQuestVR</a>."