githubpages:
  template: single_page.html.j2
  url: github-pages.html
  content:
      breadcrumbs:
        -
          url: index.html
          link: Home
        -
          url: github-pages.html
          link: Github Pages
      title: "Github Pages"
      header: "This page is a source of information for github pages."
      header_image:
        src: "./images/GitHub_Logo_White.png"
        alt: "Background header for Shoseki, a fractal that was pushed through Googles' Deep Dream"
      content: |
        <div>
          <h2>Rules of building on <a href="https://pages.github.com/">github pages</a> :</h2>
          <ol>
            <li>Create an entirely public repository on github.com named YOURACCOUNTNAME.github.io .</li>
            <li>No server side component so pages must be regenerated each time.</li>
            <li>Private files may be uploaded but they will need to be encrypted (e.g. using Ansible Vault)</li>
            <li>This means API keys etc will need to be stored in Ansible Vault before being consumed by Ansible, they cannot be made public due to abuse potential.</li>
            <li>No mysql or other database, so data will need to be stored in sqlite or equivalent, or json file to be queried client side.</li>
            <li>As the build is automatic, the commit message has been set to the build id.</li>
            <li>This entire project is public and cloneable, feel free to create a copy and create your own website using it!</li>
          </ol>
          <h2>To reproduce this project :</h2>
          <ol>
            <li>Install git, ansible and npm on your local machine.</li>
            <li>To test that everything is set up correctly, you should be able to run "ansible-playbook --version", "git --version" and "npm --version"</li>
            <li>Fork the <a href="https://github.com/Craigmoore/craigmoore.github.io">repository</a>.</li>
            <li>Clone a local copy of your repository by using the git clone command on the command line.</li>
            <li>Change directory into the project by typing "cd project-name"</li>
            <li>You can now create/edit/delete the data used to generate the pages in ansible/variables/site.yml and ansible/variables/page/pagename.yml. One caveat is that each page must have a unique "machine name" key at the top of the structure for the files to not clash when they automatically get stitched together to create content.</li>
            <li>Once you have finished editing, to regenerate the site, from the root folder type "ansible-playbook ansible/commands/regenerate_site.yml".</li>
            <li>Warning! This will git add everything in the folder, commit and push! Do not add anything private to this repo or else it will automatically be made public, and you will need to delete the repository and start again.</li>
          </ol>
        </div>
      footer: "Github.com is owned by <a href=\"https://www.microsoft.com\">Microsoft.</a>"