index:
  template: single_page.html.j2
  url: index.html
  content:
      breadcrumbs:
        -
          url: index.html
          link: Home
      title: "Hello World"
      header: "This is a sample page while building out this Ansible-based static sitebuilder project."
      header_image:
        src: "./images/shoseki.png"
        alt: "Background header for Shoseki, a fractal that was pushed through Googles' Deep Dream"
      content: |
        <div>
          <h2>This is a basic site to demonstrate currently github pages and Banter.</h2>
          <ol>
            <li>Click <a href="./banter.html">here</a> for a page about creating content for the Banter application.</li>
            <li>Click <a href="./github-pages.html">here</a> for a page about using github pages.</li>
          </ol>
        </div>
      footer: ""