site_url: "http://craigmoore.github.io"
header: "craigmoore.github.io"
social_media_links:
  -
    url: https://github.com/Craigmoore
    link: github
  -
    url: https://www.linkedin.com/in/craigalexandermoore/
    link: linkedIn
  -
    url: https://twitter.com/Shoseki
    link: twitter
  -
    url: https://www.twitch.tv/shoseki
    link: twitch
  -
    url: "mailto:craigmoore@flashygraphics.co.uk"
    link: email
navigate_row: "Site Navigation Row"
footer: "Copyright © 2023"
info:
  -
    markup: "Craig Moore is <a href=\"https://www.linkedin.com/in/craigalexandermoore/\">currently available to hire</a> for Drupal and Typescript contract work."
success:
  -
    markup: "Here's a sample success!"
warning:
  -
    markup: "Here's a sample warning!"
error: 
  -
    markup: "Here's a sample error!"
